$(document).ready(function(){
	$("#login").on("click",function(){
		$("#logintable").toggle(1000);
		//$("p").toggle(300);
		$("#regtable").hide(200);
		})
	$("#reg").on("click",function(){
		$("#regtable").toggle(1000);
		$("p").toggle(300);
		$("#logintable").hide(200);
		})
	});